name: gsplat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorlog==6.10.1
      - comm==0.2.3
      - debugpy==1.8.19
      - decorator==5.2.1
      - embreex==2.17.7.post7
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.20.0
      - fsspec==2025.12.0
      - gsplat==1.5.3+pt24cu124
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - ipykernel==7.1.0
      - ipython==8.37.0
      - jaxtyping==0.3.4
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - lxml==6.0.2
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgspec==0.20.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.10.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plyfile==1.1.3
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycollada==0.9.2
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.30.0
      - rtree==1.4.1
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - stack-data==0.6.3
      - svg-path==7.0
      - sympy==1.14.0
      - torch==2.4.0+cu124
      - torchvision==0.19.0+cu124
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.10.1
      - triton==3.0.0
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - vhacdx==0.0.10
      - viser==1.0.16
      - wadler-lindig==0.1.7
      - wcwidth==0.2.14
      - websockets==15.0.1
      - xxhash==3.6.0
      - yourdfpy==0.0.58
