name: gsplat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - torchvision=0.19.0
  - pytorch-cuda=12.4
  - pytorch=2.4.0
  - torchaudio=2.4.0
  - plyfile
  - viser
pip:
  - backports.zstd==1.2.0
  - Brotli==1.2.0
  - certifi==2025.11.12
  - charset-normalizer==3.4.4
  - colorama==0.4.6
  - docstring_parser==0.17.0
  - eval_type_backport==0.3.1
  - filelock==3.20.1
  - fsspec==2025.12.0
  - gmpy2==2.2.1
  - gsplat==1.5.3
  - h2==4.3.0
  - hpack==4.1.0
  - hyperframe==6.1.0
  - idna==3.11
  - imageio==2.37.0
  - importlib_metadata==8.7.0
  - jaxtyping==0.3.4
  - Jinja2==3.1.6
  - lazy_loader==0.4
  - lxml==6.0.2
  - markdown-it-py==4.0.0
  - MarkupSafe==3.0.3
  - mdurl==0.1.2
  - mpmath==1.3.0
  - msgspec==0.20.0
  - networkx==3.4.2
  - ninja==1.13.0
  - nodeenv==1.10.0
  - numpy==2.2.6
  - opencv-python==4.12.0
  - opencv-python-headless==4.12.0
  - packaging==25.0
  - pillow==12.0.0
  - pip==25.3
  - plyfile==1.1
  - psutil==7.1.3
  - Pygments==2.19.2
  - PySocks==1.7.1
  - PyWavelets==1.8.0
  - PyYAML==6.0.3
  - requests==2.32.5
  - rich==14.2.0
  - scikit-image==0.25.2
  - scipy==1.15.2
  - setuptools==80.9.0
  - shtab==1.8.0
  - six==1.17.0
  - sympy==1.14.0
  - tifffile==2025.2.18
  - torch==2.4.0
  - torchaudio==2.4.0
  - torchvision==0.19.0
  - tqdm==4.67.1
  - trimesh==4.10.1
  - triton==3.0.0
  - typeguard==4.4.4
  - typing_extensions==4.15.0
  - tyro==0.9.35
  - urllib3==2.6.2
  - viser==1.0.16
  - wadler_lindig==0.1.7
  - websockets==15.0.1
  - wheel==0.45.1
  - yourdfpy==0.0.57
  - zipp==3.23.0