name: vmamba
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gcc_linux-64=12.3
  - sysroot_linux-64=2.17
  - gxx_linux-64=12.3
  - ipykernel
pip:
  - asttokens==3.0.1
  - chardet==5.2.0
  - cloudpickle==3.1.2
  - comm==0.2.3
  - contourpy==1.3.2
  - cycler==0.12.1
  - debugpy==1.8.19
  - decorator==5.2.1
  - einops==0.8.1
  - exceptiongroup==1.3.1
  - executing==2.2.1
  - filelock==3.20.0
  - fonttools==4.61.1
  - fsspec==2025.12.0
  - fvcore==0.1.5.post20221221
  - iniconfig==2.3.0
  - iopath==0.1.10
  - ipykernel==7.1.0
  - ipython==8.37.0
  - jedi==0.19.2
  - Jinja2==3.1.6
  - jupyter_client==8.7.0
  - jupyter_core==5.9.1
  - kiwisolver==1.4.9
  - MarkupSafe==2.1.5
  - matplotlib==3.10.8
  - matplotlib-inline==0.2.1
  - mpmath==1.3.0
  - nest_asyncio==1.6.0
  - networkx==3.4.2
  - ninja==1.13.0
  - numpy==2.2.6
  - nvidia-cublas-cu12==12.4.5.8
  - nvidia-cuda-cupti-cu12==12.4.127
  - nvidia-cuda-nvrtc-cu12==12.4.127
  - nvidia-cuda-runtime-cu12==12.4.127
  - nvidia-cudnn-cu12==9.1.0.70
  - nvidia-cufft-cu12==11.2.1.3
  - nvidia-curand-cu12==10.3.5.147
  - nvidia-cusolver-cu12==11.6.1.9
  - nvidia-cusparse-cu12==12.3.1.170
  - nvidia-cusparselt-cu12==0.6.2
  - nvidia-nccl-cu12==2.21.5
  - nvidia-nvjitlink-cu12==12.4.127
  - nvidia-nvtx-cu12==12.4.127
  - packaging==25.0
  - pandas==2.3.3
  - parso==0.8.5
  - pexpect==4.9.0
  - pickleshare==0.7.5
  - pillow==12.0.0
  - pip==25.3
  - platformdirs==4.5.1
  - pluggy==1.6.0
  - portalocker==3.2.0
  - prompt_toolkit==3.0.52
  - protobuf==6.33.2
  - psutil==7.2.1
  - ptyprocess==0.7.0
  - pure_eval==0.2.3
  - Pygments==2.19.2
  - pyparsing==3.3.1
  - pytest==9.0.2
  - python-dateutil==2.9.0.post0
  - pytz==2025.2
  - PyYAML==6.0.3
  - pyzmq==27.1.0
  - seaborn==0.13.2
  - selective_scan==0.0.2
  - setuptools==80.9.0
  - six==1.17.0
  - stack_data==0.6.3
  - submitit==1.5.4
  - sympy==1.13.1
  - tabulate==0.9.0
  - tensorboardX==2.6.4
  - termcolor==3.3.0
  - timm==0.4.12
  - tomli==2.3.0
  - torch==2.6.0+cu124
  - torchaudio==2.6.0+cu124
  - torchvision==0.21.0+cu124
  - tornado==6.5.4
  - tqdm==4.67.1
  - traitlets==5.14.3
  - triton==3.2.0
  - typing_extensions==4.15.0
  - tzdata==2025.3
  - wcwidth==0.2.14
  - wheel==0.45.1
  - yacs==0.1.8